"""
MongoDB Database Schema for ChatBot Service
Database: chatbot_db (MongoDB Atlas)
Collections: 6 main collections

Document Structure:
- conversations: Chat conversations
- messages: Individual messages in conversations
- chatbot_memory: AI learning and memory storage
- uploaded_files: File upload metadata
- users: User information (optional)
- user_settings: User preferences and settings
"""

# ============================================================================
# COLLECTION 1: conversations
# ============================================================================
"""
Purpose: Store chat conversations
Index: user_id, created_at, is_archived
"""
conversation_schema = {
    "_id": "ObjectId",  # Auto-generated by MongoDB
    "user_id": "string",  # User identifier (can be session ID or user ID)
    "model": "string",  # 'grok-3', 'gpt-4', 'qwen-local', etc.
    "title": "string",  # Conversation title (auto-generated from first message)
    "system_prompt": "string",  # Custom system prompt (optional)
    "total_messages": "int",  # Count of messages
    "total_tokens": "int",  # Total tokens used
    "is_archived": "bool",  # Archived status
    "metadata": {
        "temperature": "float",
        "max_tokens": "int",
        "top_p": "float",
        "custom_settings": "object"
    },
    "created_at": "ISODate",  # Creation timestamp
    "updated_at": "ISODate"   # Last update timestamp
}

conversation_example = {
    "_id": "ObjectId('673e5f8a9b1d2c3f4a5b6c7d')",
    "user_id": "anonymous_session_123abc",
    "model": "grok-3",
    "title": "Python Code Review Discussion",
    "system_prompt": "You are a helpful AI assistant.",
    "total_messages": 15,
    "total_tokens": 8500,
    "is_archived": False,
    "metadata": {
        "temperature": 0.7,
        "max_tokens": 2048,
        "top_p": 0.95,
        "custom_settings": {}
    },
    "created_at": "ISODate('2025-11-09T10:30:00Z')",
    "updated_at": "ISODate('2025-11-09T11:45:00Z')"
}


# ============================================================================
# COLLECTION 2: messages
# ============================================================================
"""
Purpose: Store individual messages within conversations
Index: conversation_id, created_at, role
"""
message_schema = {
    "_id": "ObjectId",
    "conversation_id": "ObjectId",  # Reference to conversations._id
    "role": "string",  # 'user', 'assistant', 'system'
    "content": "string",  # Message text content
    "images": [
        {
            "url": "string",  # Image URL (local path or cloud URL)
            "cloud_url": "string",  # PostImages cloud URL (permanent, shareable)
            "delete_url": "string",  # PostImages delete URL (to remove image)
            "caption": "string",
            "size": "int",  # File size in bytes
            "mime_type": "string",
            "generated": "bool",  # True if AI-generated
            "service": "string"  # 'postimages', 'local', etc.
        }
    ],
    "files": [
        {
            "name": "string",
            "path": "string",
            "type": "string",  # File extension
            "size": "int",
            "mime_type": "string",
            "analysis_result": "string"  # AI analysis of file
        }
    ],
    "metadata": {
        "model": "string",
        "tokens": "int",
        "temperature": "float",
        "finish_reason": "string",  # 'stop', 'length', 'interrupted'
        "generation_time_ms": "int"
    },
    "version": "int",  # Message version (for edit history)
    "parent_message_id": "ObjectId",  # For message versioning
    "is_edited": "bool",
    "is_stopped": "bool",  # True if generation was stopped by user
    "created_at": "ISODate"
}

message_example = {
    "_id": "ObjectId('673e5f8a9b1d2c3f4a5b6c7e')",
    "conversation_id": "ObjectId('673e5f8a9b1d2c3f4a5b6c7d')",
    "role": "assistant",
    "content": "Here's the code review...\n\n```python\ndef example():\n    pass\n```",
    "images": [
        {
            "url": "/static/Storage/Image_Gen/img_20251109_abc123.png",
            "cloud_url": "https://i.postimg.cc/xyz789/img_20251109_abc123.png",
            "delete_url": "https://postimg.cc/delete/abc123",
            "caption": "Generated diagram",
            "size": 245680,
            "mime_type": "image/png",
            "generated": True,
            "service": "postimages"
        }
    ],
    "files": [],
    "metadata": {
        "model": "grok-3",
        "tokens": 450,
        "temperature": 0.7,
        "finish_reason": "stop",
        "generation_time_ms": 2350
    },
    "version": 1,
    "parent_message_id": None,
    "is_edited": False,
    "is_stopped": False,
    "created_at": "ISODate('2025-11-09T10:31:00Z')"
}


# ============================================================================
# COLLECTION 3: chatbot_memory
# ============================================================================
"""
Purpose: Store AI learning data and memories
Index: user_id, conversation_id, tags, created_at
"""
memory_schema = {
    "_id": "ObjectId",
    "user_id": "string",
    "conversation_id": "ObjectId",  # Optional: link to specific conversation
    "question": "string",  # User's question
    "answer": "string",  # AI's answer
    "context": "string",  # Additional context
    "images": [
        {
            "url": "string",
            "caption": "string",
            "relevance": "string"  # Why this image is saved
        }
    ],
    "rating": "int",  # 1-5 stars (user feedback)
    "tags": ["string"],  # Array of tags for categorization
    "is_public": "bool",  # Share with other users?
    "metadata": {
        "model_used": "string",
        "tokens": "int",
        "confidence_score": "float"
    },
    "created_at": "ISODate"
}

memory_example = {
    "_id": "ObjectId('673e5f8a9b1d2c3f4a5b6c7f')",
    "user_id": "anonymous_session_123abc",
    "conversation_id": "ObjectId('673e5f8a9b1d2c3f4a5b6c7d')",
    "question": "How to implement async functions in Python?",
    "answer": "Here's how to use async/await in Python...",
    "context": "Discussing Python asyncio library",
    "images": [],
    "rating": 5,
    "tags": ["python", "async", "programming"],
    "is_public": False,
    "metadata": {
        "model_used": "grok-3",
        "tokens": 380,
        "confidence_score": 0.95
    },
    "created_at": "ISODate('2025-11-09T10:35:00Z')"
}


# ============================================================================
# COLLECTION 4: uploaded_files
# ============================================================================
"""
Purpose: Track uploaded files and their analysis
Index: user_id, conversation_id, created_at
"""
uploaded_file_schema = {
    "_id": "ObjectId",
    "user_id": "string",
    "conversation_id": "ObjectId",
    "original_filename": "string",  # Original filename
    "stored_filename": "string",  # Stored filename (with hash)
    "file_path": "string",  # Full file path
    "file_type": "string",  # Extension: .pdf, .png, .py, etc.
    "file_size": "int",  # Size in bytes
    "mime_type": "string",
    "analysis_result": "string",  # AI analysis summary
    "metadata": {
        "upload_time_ms": "int",
        "analysis_time_ms": "int",
        "model_used": "string",
        "extracted_text": "string",  # For PDFs, images with OCR
        "page_count": "int",  # For PDFs
        "dimensions": {  # For images
            "width": "int",
            "height": "int"
        }
    },
    "created_at": "ISODate"
}

uploaded_file_example = {
    "_id": "ObjectId('673e5f8a9b1d2c3f4a5b6c80')",
    "user_id": "anonymous_session_123abc",
    "conversation_id": "ObjectId('673e5f8a9b1d2c3f4a5b6c7d')",
    "original_filename": "report.pdf",
    "stored_filename": "upload_20251109_abc123_report.pdf",
    "file_path": "ChatBot/Storage/uploads/upload_20251109_abc123_report.pdf",
    "file_type": "pdf",
    "file_size": 2456789,
    "mime_type": "application/pdf",
    "analysis_result": "This PDF contains a financial report with 5 pages...",
    "metadata": {
        "upload_time_ms": 450,
        "analysis_time_ms": 3200,
        "model_used": "grok-3",
        "extracted_text": "Full text extracted from PDF...",
        "page_count": 5,
        "dimensions": None
    },
    "created_at": "ISODate('2025-11-09T10:32:00Z')"
}


# ============================================================================
# COLLECTION 5: users (Optional - for future multi-user support)
# ============================================================================
"""
Purpose: Store user information and preferences
Index: email, username, created_at
"""
user_schema = {
    "_id": "ObjectId",
    "username": "string",  # Unique username
    "email": "string",  # Unique email
    "password_hash": "string",  # Hashed password (bcrypt)
    "full_name": "string",
    "avatar_url": "string",
    "role": "string",  # 'user', 'admin', 'developer'
    "is_active": "bool",
    "api_quota_daily": "int",  # API calls per day
    "preferences": {
        "default_model": "string",
        "theme": "string",  # 'dark', 'light'
        "language": "string",  # 'vi', 'en'
        "auto_save": "bool"
    },
    "created_at": "ISODate",
    "last_login": "ISODate",
    "last_ip": "string"
}


# ============================================================================
# COLLECTION 6: user_settings
# ============================================================================
"""
Purpose: Store user-specific settings and configurations
Index: user_id
"""
user_settings_schema = {
    "_id": "ObjectId",
    "user_id": "string",
    "chatbot_settings": {
        "default_model": "string",
        "temperature": "float",
        "max_tokens": "int",
        "system_prompt": "string",
        "enable_memory": "bool",
        "enable_tools": "bool",
        "enable_image_gen": "bool"
    },
    "ui_settings": {
        "theme": "string",
        "font_size": "string",
        "code_theme": "string",
        "show_tokens": "bool",
        "auto_scroll": "bool"
    },
    "notification_settings": {
        "enable_notifications": "bool",
        "email_notifications": "bool"
    },
    "updated_at": "ISODate"
}


# ============================================================================
# MONGODB QUERY EXAMPLES
# ============================================================================

QUERY_EXAMPLES = """
# 1. Create new conversation
db.conversations.insert_one({
    "user_id": "anonymous_session_123abc",
    "model": "grok-3",
    "title": "New Chat",
    "total_messages": 0,
    "total_tokens": 0,
    "is_archived": False,
    "created_at": datetime.utcnow(),
    "updated_at": datetime.utcnow()
})

# 2. Get all conversations for a user (latest first)
db.conversations.find(
    {"user_id": "anonymous_session_123abc", "is_archived": False}
).sort("updated_at", -1).limit(20)

# 3. Get all messages in a conversation
db.messages.find(
    {"conversation_id": ObjectId("673e5f8a9b1d2c3f4a5b6c7d")}
).sort("created_at", 1)

# 4. Add message to conversation
db.messages.insert_one({
    "conversation_id": ObjectId("673e5f8a9b1d2c3f4a5b6c7d"),
    "role": "user",
    "content": "Hello, AI!",
    "images": [],
    "files": [],
    "metadata": {},
    "version": 1,
    "is_edited": False,
    "created_at": datetime.utcnow()
})

# 5. Search memory by tags
db.chatbot_memory.find(
    {"tags": {"$in": ["python", "async"]}}
).sort("created_at", -1)

# 6. Get conversation with messages (aggregation)
db.conversations.aggregate([
    {"$match": {"_id": ObjectId("673e5f8a9b1d2c3f4a5b6c7d")}},
    {"$lookup": {
        "from": "messages",
        "localField": "_id",
        "foreignField": "conversation_id",
        "as": "messages"
    }},
    {"$project": {
        "_id": 1,
        "title": 1,
        "model": 1,
        "messages": {"$sortArray": {"input": "$messages", "sortBy": {"created_at": 1}}}
    }}
])

# 7. Update conversation (increment message count)
db.conversations.update_one(
    {"_id": ObjectId("673e5f8a9b1d2c3f4a5b6c7d")},
    {
        "$inc": {"total_messages": 1, "total_tokens": 450},
        "$set": {"updated_at": datetime.utcnow()}
    }
)

# 8. Archive old conversations (older than 30 days)
from datetime import datetime, timedelta
db.conversations.update_many(
    {"updated_at": {"$lt": datetime.utcnow() - timedelta(days=30)}},
    {"$set": {"is_archived": True}}
)

# 9. Delete conversation and all messages (cascade)
conversation_id = ObjectId("673e5f8a9b1d2c3f4a5b6c7d")
db.messages.delete_many({"conversation_id": conversation_id})
db.conversations.delete_one({"_id": conversation_id})

# 10. Get statistics
db.conversations.aggregate([
    {"$group": {
        "_id": "$user_id",
        "total_conversations": {"$sum": 1},
        "total_messages": {"$sum": "$total_messages"},
        "total_tokens": {"$sum": "$total_tokens"}
    }}
])
"""


# ============================================================================
# VALIDATION RULES (MongoDB Schema Validation)
# ============================================================================

def create_validation_rules():
    """
    Create MongoDB schema validation rules
    Run this once to set up validation
    """
    validation_rules = {
        "conversations": {
            "$jsonSchema": {
                "bsonType": "object",
                "required": ["user_id", "model", "created_at"],
                "properties": {
                    "user_id": {"bsonType": "string"},
                    "model": {"bsonType": "string"},
                    "title": {"bsonType": "string"},
                    "total_messages": {"bsonType": "int", "minimum": 0},
                    "total_tokens": {"bsonType": "int", "minimum": 0},
                    "is_archived": {"bsonType": "bool"},
                    "created_at": {"bsonType": "date"},
                    "updated_at": {"bsonType": "date"}
                }
            }
        },
        "messages": {
            "$jsonSchema": {
                "bsonType": "object",
                "required": ["conversation_id", "role", "content", "created_at"],
                "properties": {
                    "conversation_id": {"bsonType": "objectId"},
                    "role": {"enum": ["user", "assistant", "system"]},
                    "content": {"bsonType": "string"},
                    "images": {"bsonType": "array"},
                    "files": {"bsonType": "array"},
                    "version": {"bsonType": "int", "minimum": 1},
                    "is_edited": {"bsonType": "bool"},
                    "created_at": {"bsonType": "date"}
                }
            }
        }
    }
    return validation_rules
